### ISSUE TITLE
Implement Gateway & Component management

### ISSUE THREAD

**Issue by cambierr** [TheThingsNetwork/java-app-sdk#42]

**Comment by FokkeZB** [comment]
Although I welcome this, it does expand the SDK beyond the current "app" scope. What would you suggest @johanstokking?

**Comment by johanstokking** [comment]
Yes, I can imagine it's very welcome but indeed this is beyond the application scope.

The application scope, on a high level, interfaces with the Handler through the Application Manager and Data API, and uses the Account Server for authentication. Gateway and component management is resource management on the Account Server.

I'd suggest introducing a new repository for this. Not sure what's common in the Java ecosystem though.

**Comment by cambierr** [comment]
Well, since it's related to account, my opinion is that we could include this in the account library.

Then, we should rename this repo into something like java-sdk and just drop "app" ? 

When building the project, all artifacts will be separated anyway and individually releasable, even if sitting in the same git repo.

**Comment by johanstokking** [comment]
OK sounds good

**Comment by FokkeZB** [comment]
I guess how we deal with this also depends on the language and options to separate different parts of the SDK to keep it lightweight. For example, for Nodejs I'd suggest splitting it into ttn-data, ttn-account etc with ttn depending on all of them. Much like lodash, allowing you to also just depend on what you need instead of the all in one.
